name: Build desktop app

on:
  push:
    paths:
      - 'packages/niivue-desktop/**'
      - '.github/workflows/build_desktop.yml'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Niivue library
        run: npm run build:niivue

      # - name: build-linux
      #   if: matrix.os == 'ubuntu-latest'
      #   run: npm run build:desktop-linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:desktop-mac

      # - name: build-win
      #   if: matrix.os == 'windows-latest'
      #   run: npm run build:desktop-win

      - name: upload artifacts mac
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: packages/niivue-desktop/dist/*.dmg
          retention-days: 14